# RIGEL Engine — Shell Integration
# Generated by RIGEL installer. Do not edit manually.
# Source this from your .zshrc or .bashrc

# ── Determine install directory from script location ─────────────────────────
if [[ -n "$BASH_SOURCE" ]]; then
    _RIGEL_INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [[ -n "$ZSH_VERSION" ]]; then
    _RIGEL_INSTALL_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
else
    _RIGEL_INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

# ── Color helpers (zsh + bash) ───────────────────────────────────────────────
if [[ -n "$ZSH_VERSION" ]]; then
    _rigel_color_red="%F{red}"
    _rigel_color_green="%F{green}"
    _rigel_color_yellow="%F{yellow}"
    _rigel_color_blue="%F{blue}"
    _rigel_color_cyan="%F{cyan}"
    _rigel_color_magenta="%F{magenta}"
    _rigel_color_white="%F{white}"
    _rigel_color_dim="%F{8}"
    _rigel_color_reset="%f"
    _rigel_color_bold="%B"
    _rigel_color_bold_off="%b"
else
    _rigel_color_red='\033[0;31m'
    _rigel_color_green='\033[0;32m'
    _rigel_color_yellow='\033[1;33m'
    _rigel_color_blue='\033[0;34m'
    _rigel_color_cyan='\033[0;36m'
    _rigel_color_magenta='\033[0;35m'
    _rigel_color_white='\033[0;37m'
    _rigel_color_dim='\033[2m'
    _rigel_color_reset='\033[0m'
    _rigel_color_bold='\033[1m'
    _rigel_color_bold_off='\033[22m'
fi

# ── Logging ──────────────────────────────────────────────────────────────────
rigel_log() {
    local level="$1"
    local message="$2"
    local timestamp
    timestamp=$(date '+%H:%M:%S')

    if [[ -n "$ZSH_VERSION" ]]; then
        case "$level" in
            "info"|"INFO")
                print -P "${_rigel_color_blue}[INFO]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            "warn"|"WARN"|"warning"|"WARNING")
                print -P "${_rigel_color_yellow}[WARN]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            "error"|"ERROR")
                print -P "${_rigel_color_red}[ERROR]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            "success"|"SUCCESS")
                print -P "${_rigel_color_green}[SUCCESS]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            *)
                print -P "${_rigel_color_white}[LOG]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
        esac
    else
        case "$level" in
            "info"|"INFO")
                echo -e "${_rigel_color_blue}[INFO]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            "warn"|"WARN"|"warning"|"WARNING")
                echo -e "${_rigel_color_yellow}[WARN]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            "error"|"ERROR")
                echo -e "${_rigel_color_red}[ERROR]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            "success"|"SUCCESS")
                echo -e "${_rigel_color_green}[SUCCESS]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
            *)
                echo -e "${_rigel_color_white}[LOG]${_rigel_color_reset} ${_rigel_color_dim}[$timestamp]${_rigel_color_reset} $message" ;;
        esac
    fi
}

alias rigel_info='rigel_log info'
alias rigel_warn='rigel_log warn'
alias rigel_error='rigel_log error'
alias rigel_success='rigel_log success'

# ── Spinner animation ────────────────────────────────────────────────────────
rigel_spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'
    local message="${2:-Processing}"

    while kill -0 "$pid" 2>/dev/null; do
        local temp=${spinstr#?}
        printf "\r\033[36m[%c]\033[0m \033[90m%s...\033[0m" "$spinstr" "$message"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
    done
    printf "\r\033[K\n"
}

# ── D-Bus query executor ─────────────────────────────────────────────────────
rigel_execute_query() {
    local method="$1"
    shift
    local message=""
    local args=()
    local no_animate=false

    # Parse arguments
    while [ $# -gt 0 ]; do
        case "$1" in
            --no_animate)
                no_animate=true
                shift ;;
            *"Processing"*|*"Querying"*|*"Synthesizing"*|*"Transcribing"*|*"Retrieving"*|*"Analyzing"*)
                message="$1"
                shift
                break ;;
            *)
                args+=("$1")
                shift ;;
        esac
    done

    if [ -z "$message" ]; then
        message="Querying RIGEL"
    fi

    # Temporary files
    local temp_file
    temp_file=$(mktemp)
    local raw_file
    raw_file=$(mktemp)
    local error_file
    error_file=$(mktemp)
    local timeout_duration=120

    # Disable job control messages temporarily
    set +m

    # Execute D-Bus call in background with timeout
    {
        timeout $timeout_duration dbus-send --system \
            --dest=com.rigel.RigelService \
            --type=method_call \
            --print-reply \
            --reply-timeout=120000 \
            /com/rigel/RigelService \
            "com.rigel.RigelService.$method" \
            "${args[@]}" 2>"$error_file" > "$raw_file"
        echo $? > "${temp_file}.exit"
    } &

    local query_pid=$!
    local spinner_pid=""

    if [ "$no_animate" = false ]; then
        { rigel_spinner $query_pid "$message"; } &
        spinner_pid=$!
    fi

    wait $query_pid 2>/dev/null
    local wait_exit=$?

    if [ -n "$spinner_pid" ]; then
        kill $spinner_pid 2>/dev/null
        wait $spinner_pid 2>/dev/null
    fi

    set -m

    # Read exit code
    local exit_code=1
    if [ -f "${temp_file}.exit" ]; then
        exit_code=$(cat "${temp_file}.exit")
        rm -f "${temp_file}.exit"
    fi

    # Parse the response
    local response=""
    if [ $exit_code -eq 0 ] && [ -f "$raw_file" ]; then
        response=$(awk '
        BEGIN { in_string = 0; response = "" }
        /string "/ {
            in_string = 1
            start = index($0, "string \"") + 8
            content = substr($0, start)
            if (content ~ /"$/) {
                gsub(/"$/, "", content)
                response = content
                in_string = 0
            } else {
                response = content "\n"
            }
            next
        }
        in_string == 1 {
            if ($0 ~ /"$/) {
                gsub(/"$/, "", $0)
                response = response $0
                in_string = 0
            } else {
                response = response $0 "\n"
            }
        }
        END {
            gsub(/\n$/, "", response)
            print response
        }
        ' "$raw_file")
    fi

    local error_output
    error_output=$(cat "$error_file" 2>/dev/null)

    rm -f "$temp_file" "$raw_file" "$error_file"

    if [ $exit_code -eq 124 ]; then
        rigel_error "Query timed out after 120 seconds"
        return 1
    elif [ $exit_code -ne 0 ]; then
        if [ -n "$error_output" ]; then
            rigel_error "D-Bus call failed: $error_output"
        else
            rigel_error "D-Bus call failed with exit code $exit_code"
        fi
        return 1
    elif [ -z "$response" ]; then
        rigel_error "No response received from RIGEL service"
        if [ -n "$error_output" ]; then
            rigel_warn "Error output: $error_output"
        fi
        return 1
    else
        response=$(printf '%s' "$response" | sed -E 's/^\s*\[\-\]\s*Querying RIGEL\.*\s*//')
        printf "%s\n" "$response"
        return 0
    fi
}

# ── Check if service is running ──────────────────────────────────────────────
_rigel_service_running() {
    dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply \
        /org/freedesktop/DBus org.freedesktop.DBus.NameHasOwner \
        string:com.rigel.RigelService 2>/dev/null | grep -q "boolean true"
}

# ── Query ────────────────────────────────────────────────────────────────────
rigel_query() {
    local no_animate=false
    local query_args=()

    while [ $# -gt 0 ]; do
        case "$1" in
            --no_animate)
                no_animate=true
                shift ;;
            *)
                query_args+=("$1")
                shift ;;
        esac
    done

    if [ ${#query_args[@]} -eq 0 ]; then
        rigel_error "Usage: rigel_query [--no_animate] 'your question here'"
        return 1
    fi

    local query="${query_args[*]}"

    if [ "$no_animate" = false ]; then
        rigel_info "Querying RIGEL: $query"
    fi

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    if [ "$no_animate" = true ]; then
        rigel_execute_query "Query" --no_animate "string:\"$query\"" "Processing query"
    else
        rigel_execute_query "Query" "string:\"$query\"" "Processing query"
    fi
}

# ── Query with memory ────────────────────────────────────────────────────────
rigel_memory() {
    if [ $# -lt 2 ]; then
        rigel_error "Usage: rigel_memory 'conversation_id' 'your question here'"
        rigel_info "Example: rigel_memory 'chat_001' 'Remember that I like Python programming'"
        return 1
    fi

    local id="$1"
    shift
    local query="$*"
    rigel_info "Querying RIGEL with memory (ID: $id): $query"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "QueryWithMemory" "string:\"$query\"" "string:\"$id\"" "Processing memory query"
}

# ── Think (reasoning) ────────────────────────────────────────────────────────
rigel_think() {
    if [ $# -eq 0 ]; then
        rigel_error "Usage: rigel_think 'your question here'"
        rigel_info "Uses the model's reasoning/thinking capability before answering."
        return 1
    fi

    local query="$*"
    rigel_info "Thinking about: $query"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "QueryThink" "string:\"$query\"" "Processing reasoning"
}

# ── Natural Language ─────────────────────────────────────────────────────────
rigel_natural_language() {
    if [ $# -eq 0 ]; then
        rigel_error "Usage: rigel_natural_language [conversation_id] 'your request here'"
        rigel_info "Examples:"
        rigel_info "  rigel_natural_language 'check disk usage and explain it simply'"
        rigel_info "  rigel_natural_language 'chat_001' 'set volume to 50 and confirm'"
        return 1
    fi

    local id=""
    local query=""

    if [ $# -eq 1 ]; then
        id="nl_$(date +%s)"
        query="$1"
    else
        id="$1"
        shift
        query="$*"
    fi

    if [ -z "$query" ]; then
        rigel_error "Empty query. Please provide a request."
        return 1
    fi

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "RigelNaturalLanguage" "string:\"$query\"" "string:\"$id\"" "Processing natural language request"
}
alias rigel_nl='rigel_natural_language'

# ── Tools ────────────────────────────────────────────────────────────────────
rigel_tools() {
    if [ $# -eq 0 ]; then
        rigel_error "Usage: rigel_tools 'your task here'"
        return 1
    fi

    local user_query="$*"
    local current_dir
    current_dir="$(pwd)"

    local enhanced_query
    enhanced_query="Working Directory: $current_dir | User request: $user_query"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running."
        return 1
    fi

    rigel_info "Running toolcall..."

    local tool_output
    tool_output="$(
        rigel_execute_query \
            QueryWithTools \
            --no_animate \
            "string:\"$enhanced_query\""
    )"

    rigel_info "Summarizing tool output..."

    local safe_tool_output="$tool_output"
    if [ -z "$safe_tool_output" ]; then
        safe_tool_output="tool_returned_no_output"
    fi

    local max_chars=60000
    if [ ${#safe_tool_output} -gt $max_chars ]; then
        safe_tool_output="${safe_tool_output:0:$max_chars}\n[Note: Output truncated to ${max_chars} chars]"
    fi

    local escaped_output
    escaped_output="$(printf '%s' "$safe_tool_output" | sed -e 's/{/{{/g' -e 's/}/}}/g')"

    local summary_prompt="Summarize the following tool output for the user:\n${escaped_output}"

    rigel_execute_query \
        Query \
        --no_animate \
        "string:\"$summary_prompt\""
}

# ── Vision ───────────────────────────────────────────────────────────────────
rigel_vision() {
    if [ $# -lt 1 ]; then
        rigel_error "Usage: rigel_vision 'path/to/image.png' ['optional prompt']"
        rigel_info "Example: rigel_vision 'screenshot.png' 'Describe what you see'"
        return 1
    fi

    local image_path="$1"
    local prompt="${2:-Describe what you see in this image.}"

    if [ ! -f "$image_path" ]; then
        rigel_error "Image file not found: $image_path"
        return 1
    fi

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Analyzing image: $image_path"
    rigel_execute_query "AnalyzeImage" "string:\"$image_path\"" "string:\"$prompt\"" "Analyzing image"
}

# ── Speech Synthesis ─────────────────────────────────────────────────────────
rigel_speak() {
    if [ -z "$1" ]; then
        rigel_error "Usage: rigel_speak 'text to synthesize' [mode] [voice]"
        rigel_info "Modes: chunk (default), stream, file"
        return 1
    fi

    local text="$1"
    local mode="${2:-chunk}"
    local voice="${3:-}"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Synthesizing text with mode: $mode"
    local response
    if [ -n "$voice" ]; then
        response=$(rigel_execute_query "SynthesizeText" "string:\"$text\"" "string:$mode" "string:$voice" "Synthesizing speech")
    else
        response=$(rigel_execute_query "SynthesizeText" "string:\"$text\"" "string:$mode" "string:" "Synthesizing speech")
    fi

    if [ $? -eq 0 ] && [ -n "$response" ]; then
        rigel_success "$response"
    else
        rigel_error "Failed to synthesize text"
        return 1
    fi
}

# ── Voice Management ─────────────────────────────────────────────────────────
rigel_voice_list() {
    rigel_info "Retrieving available voices..."

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "ListVoices" "Retrieving voice list"
}

rigel_voice_set() {
    if [ -z "$1" ]; then
        rigel_error "Usage: rigel_voice_set 'voice_name'"
        rigel_info "Use 'rigel_voice_list' to see available voices."
        return 1
    fi

    local voice="$1"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Setting voice to: $voice"
    rigel_execute_query "SetVoice" "string:\"$voice\"" "Retrieving voice list"
}

rigel_voice_clone() {
    if [ $# -lt 2 ]; then
        rigel_error "Usage: rigel_voice_clone 'path/to/sample.mp3' 'voice_name' [language]"
        rigel_info "Example: rigel_voice_clone 'my_voice.mp3' 'my_clone'"
        return 1
    fi

    local mp3_path="$1"
    local voice_name="$2"
    local language="${3:-English (U.S.)}"

    if [ ! -f "$mp3_path" ]; then
        rigel_error "Audio file not found: $mp3_path"
        return 1
    fi

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Cloning voice from: $mp3_path"
    rigel_execute_query "CloneVoice" "string:\"$mp3_path\"" "string:\"$voice_name\"" "string:\"$language\"" "Cloning voice"
}

# ── Audio Transcription ──────────────────────────────────────────────────────
rigel_transcribe() {
    if [ -z "$1" ]; then
        rigel_error "Usage: rigel_transcribe '/path/to/audio/file' [model]"
        rigel_info "Models: tiny (default), base, small, medium, large"
        return 1
    fi

    local audio_file="$1"
    local model="${2:-small}"

    if [ ! -f "$audio_file" ]; then
        rigel_error "Audio file not found: $audio_file"
        return 1
    fi

    rigel_info "Transcribing audio file: $audio_file (model: $model)"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "RecognizeAudio" "string:\"$audio_file\"" "string:\"$model\"" "Transcribing audio"
}

# ── Live Voice Recognition ───────────────────────────────────────────────────
rigel_live_transcribe() {
    if [ $# -lt 1 ]; then
        rigel_error "Usage: rigel_live_transcribe start|stop|status [config_json]"
        rigel_info "Examples:"
        rigel_info "  rigel_live_transcribe start"
        rigel_info "  rigel_live_transcribe start '{\"model\":\"tiny.en\",\"capture_device\":-1}'"
        rigel_info "  rigel_live_transcribe stop"
        rigel_info "  rigel_live_transcribe status"
        return 1
    fi

    local action="$1"
    local config_json="${2:-{}}"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    case "$action" in
        start)
            rigel_info "Starting live voice recognition..."
            rigel_execute_query "LiveVoiceRecognition" "string:start" "string:$config_json" "Starting live recognition"
            ;;
        stop)
            rigel_info "Stopping live voice recognition..."
            rigel_execute_query "LiveVoiceRecognition" "string:stop" "string:$config_json" "Stopping live recognition"
            ;;
        status)
            rigel_execute_query "LiveVoiceRecognition" "string:status" "string:$config_json" "Checking recognition status"
            ;;
        *)
            rigel_error "Unknown action: $action. Use start, stop, or status."
            return 1
            ;;
    esac
}

# ── Coding Agent ─────────────────────────────────────────────────────────────
rigel_coding_generate() {
    if [ $# -lt 1 ]; then
        rigel_error "Usage: rigel_coding_generate 'specification' [language]"
        rigel_info "Example: rigel_coding_generate 'Create a REST API for a todo app' python"
        return 1
    fi

    local spec="$1"
    local lang="${2:-python}"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Generating code ($lang): $spec"
    rigel_execute_query "CodingAgentGenerateCode" "string:\"$spec\"" "string:\"$lang\"" "Generating code"
}

rigel_coding_review() {
    if [ $# -lt 1 ]; then
        rigel_error "Usage: rigel_coding_review 'path/to/code.py' [language]"
        rigel_info "Example: rigel_coding_review '~/project/main.py' python"
        return 1
    fi

    local file_path="$1"
    local lang="${2:-python}"

    if [ ! -f "$file_path" ]; then
        rigel_error "File not found: $file_path"
        return 1
    fi

    local code
    code=$(cat "$file_path")

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Reviewing code: $file_path"
    rigel_execute_query "CodingAgentReviewCode" "string:\"$code\"" "string:\"$lang\"" "Reviewing code"
}

rigel_coding_debug() {
    if [ $# -lt 2 ]; then
        rigel_error "Usage: rigel_coding_debug 'path/to/code.py' 'error message' [language]"
        rigel_info "Example: rigel_coding_debug 'main.py' 'TypeError at line 42' python"
        return 1
    fi

    local file_path="$1"
    local error_msg="$2"
    local lang="${3:-python}"

    if [ ! -f "$file_path" ]; then
        rigel_error "File not found: $file_path"
        return 1
    fi

    local code
    code=$(cat "$file_path")

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Debugging code: $file_path"
    rigel_execute_query "CodingAgentDebugCode" "string:\"$code\"" "string:\"$error_msg\"" "string:\"$lang\"" "Debugging code"
}

rigel_coding_refactor() {
    if [ $# -lt 2 ]; then
        rigel_error "Usage: rigel_coding_refactor 'path/to/code.py' 'refactoring instructions' [language]"
        rigel_info "Example: rigel_coding_refactor 'main.py' 'Extract database logic into separate module' python"
        return 1
    fi

    local file_path="$1"
    local instructions="$2"
    local lang="${3:-python}"

    if [ ! -f "$file_path" ]; then
        rigel_error "File not found: $file_path"
        return 1
    fi

    local code
    code=$(cat "$file_path")

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Refactoring code: $file_path"
    rigel_execute_query "CodingAgentRefactorCode" "string:\"$code\"" "string:\"$instructions\"" "string:\"$lang\"" "Refactoring code"
}

rigel_coding_explain() {
    if [ $# -lt 1 ]; then
        rigel_error "Usage: rigel_coding_explain 'path/to/code.py' [language]"
        rigel_info "Example: rigel_coding_explain 'main.py' python"
        return 1
    fi

    local file_path="$1"
    local lang="${2:-python}"

    if [ ! -f "$file_path" ]; then
        rigel_error "File not found: $file_path"
        return 1
    fi

    local code
    code=$(cat "$file_path")

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Explaining code: $file_path"
    rigel_execute_query "CodingAgentExplainCode" "string:\"$code\"" "string:\"$lang\"" "Explaining code"
}

rigel_coding_execute() {
    if [ $# -lt 1 ]; then
        rigel_error "Usage: rigel_coding_execute 'path/to/code.py' ['[\"arg1\",\"arg2\"]']"
        rigel_info "Example: rigel_coding_execute 'script.py' '[\"--verbose\",\"--output\",\"out.txt\"]'"
        return 1
    fi

    local file_path="$1"
    local args_json="${2:-[]}"

    if [ ! -f "$file_path" ]; then
        rigel_error "File not found: $file_path"
        return 1
    fi

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Executing: $file_path"
    rigel_execute_query "CodingAgentExecuteCode" "string:\"$file_path\"" "string:\"$args_json\"" "Executing code"
}

rigel_coding_status() {
    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "CodingAgentGetStatus" "Retrieving status"
}

rigel_coding_history() {
    local n="${1:-20}"

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "CodingAgentGetHistory" "string:$n" "Retrieving history"
}

rigel_coding_launch() {
    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Launching coding agent..."
    rigel_execute_query "CodingAgentLaunch" "Launching agent"
}

rigel_coding_close() {
    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_info "Closing coding agent..."
    rigel_execute_query "CodingAgentClose" "Closing agent"
}

# ── License ──────────────────────────────────────────────────────────────────
rigel_license() {
    rigel_info "Retrieving RIGEL license information..."

    if ! _rigel_service_running; then
        rigel_error "RIGEL D-Bus service is not running. Please start the service first."
        return 1
    fi

    rigel_execute_query "GetLicenseInfo" "Retrieving license info"
}

# ── Status ───────────────────────────────────────────────────────────────────
rigel_status() {
    rigel_info "Checking RIGEL service status..."

    if ! command -v dbus-send >/dev/null 2>&1; then
        rigel_error "dbus-send not found. Install the dbus package."
        return 1
    fi

    if _rigel_service_running; then
        rigel_success "RIGEL D-Bus service is active and registered"

        if timeout 120 dbus-send --system --dest=com.rigel.RigelService \
            --type=method_call --print-reply --reply-timeout=120000 \
            /com/rigel/RigelService com.rigel.RigelService.GetLicenseInfo >/dev/null 2>&1; then
            rigel_success "RIGEL service is responding to queries"
            rigel_info "All systems operational"
        else
            rigel_warn "RIGEL service is registered but not responding properly"
            return 1
        fi
    else
        rigel_error "RIGEL D-Bus service is not registered or running"
        rigel_info "Please start the RIGEL service to enable intelligent functions"
        return 1
    fi
}

# ── Debug / Diagnostics ──────────────────────────────────────────────────────
rigel_debug() {
    rigel_info "Running RIGEL D-Bus diagnostics..."

    if ! command -v dbus-send >/dev/null 2>&1; then
        rigel_error "dbus-send command not found. Please install dbus package."
        return 1
    fi

    if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
        rigel_warn "DBUS_SESSION_BUS_ADDRESS not set"
    else
        rigel_info "D-Bus session address: $DBUS_SESSION_BUS_ADDRESS"
    fi

    rigel_info "Checking RIGEL service availability..."
    if _rigel_service_running; then
        rigel_success "RIGEL D-Bus service is registered"

        rigel_info "Testing basic D-Bus communication..."
        local test_response
        test_response=$(timeout 120 dbus-send --system \
            --dest=com.rigel.RigelService \
            --type=method_call \
            --print-reply \
            --reply-timeout=120000 \
            /com/rigel/RigelService \
            com.rigel.RigelService.GetLicenseInfo 2>&1)

        if [ $? -eq 0 ]; then
            rigel_success "D-Bus communication test successful"
            echo "$test_response" | head -5
        else
            rigel_error "D-Bus communication test failed"
            echo "$test_response"
        fi
    else
        rigel_error "RIGEL D-Bus service is not registered"
        rigel_info "Available D-Bus services:"
        dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply \
            /org/freedesktop/DBus org.freedesktop.DBus.ListNames 2>/dev/null | \
            grep -E 'string "com\.|string "org\.' | head -10
    fi
}

# ── Help ─────────────────────────────────────────────────────────────────────
rigel_help() {
    if [[ -n "$ZSH_VERSION" ]]; then
        print -P "${_rigel_color_cyan}RIGEL Runtime — Intelligent Functions${_rigel_color_reset}"
        print -P ""
        print -P "${_rigel_color_green}Basic Functions:${_rigel_color_reset}"
        print -P "  ${_rigel_color_yellow}rigel_query${_rigel_color_reset} [--no_animate] 'question' — Ask RIGEL a question"
        print -P "  ${_rigel_color_yellow}rigel_memory${_rigel_color_reset} 'id' 'question'          — Ask with conversation memory"
        print -P "  ${_rigel_color_yellow}rigel_think${_rigel_color_reset} 'question'              — Think/reason before answering"
        print -P "  ${_rigel_color_yellow}rigel_tools${_rigel_color_reset} 'task'                    — Use RIGEL with MCP tools"
        print -P "  ${_rigel_color_yellow}rigel_natural_language${_rigel_color_reset} [id] 'request' — Memory-first natural language flow"
        print -P "  ${_rigel_color_yellow}rigel_nl${_rigel_color_reset} [id] 'request'               — Short alias for rigel_natural_language"
        print -P ""
        print -P "${_rigel_color_green}Voice Functions:${_rigel_color_reset}"
        print -P "  ${_rigel_color_yellow}rigel_speak${_rigel_color_reset} 'text' [mode] [voice] — Text-to-speech synthesis"
        print -P "  ${_rigel_color_yellow}rigel_transcribe${_rigel_color_reset} '/path' [model]   — Audio-to-text transcription"
        print -P "  ${_rigel_color_yellow}rigel_voice_list${_rigel_color_reset}                     — List available voices"
        print -P "  ${_rigel_color_yellow}rigel_voice_set${_rigel_color_reset} 'name'            — Switch TTS voice"
        print -P "  ${_rigel_color_yellow}rigel_voice_clone${_rigel_color_reset} 'mp3' 'name'   — Clone a voice from audio"
        print -P "  ${_rigel_color_yellow}rigel_live_transcribe${_rigel_color_reset} start|stop|status — Live voice recognition"
        print -P ""
        print -P "${_rigel_color_green}Vision:${_rigel_color_reset}"
        print -P "  ${_rigel_color_yellow}rigel_vision${_rigel_color_reset} 'image.png' [prompt] — Analyze an image"
        print -P ""
        print -P "${_rigel_color_green}Coding Agent:${_rigel_color_reset}"
        print -P "  ${_rigel_color_yellow}rigel_coding_generate${_rigel_color_reset} 'spec' [lang]  — Generate code from spec"
        print -P "  ${_rigel_color_yellow}rigel_coding_review${_rigel_color_reset} 'file' [lang]   — Review code"
        print -P "  ${_rigel_color_yellow}rigel_coding_debug${_rigel_color_reset} 'file' 'err' [lang] — Debug code with error"
        print -P "  ${_rigel_color_yellow}rigel_coding_refactor${_rigel_color_reset} 'file' 'instr' [lang] — Refactor code"
        print -P "  ${_rigel_color_yellow}rigel_coding_explain${_rigel_color_reset} 'file' [lang]  — Explain code"
        print -P "  ${_rigel_color_yellow}rigel_coding_execute${_rigel_color_reset} 'file' [args] — Execute code"
        print -P "  ${_rigel_color_yellow}rigel_coding_status${_rigel_color_reset}                  — Coding agent status"
        print -P "  ${_rigel_color_yellow}rigel_coding_history${_rigel_color_reset} [n]           — Coding agent history"
        print -P "  ${_rigel_color_yellow}rigel_coding_launch${_rigel_color_reset}                  — Launch coding agent"
        print -P "  ${_rigel_color_yellow}rigel_coding_close${_rigel_color_reset}                   — Close coding agent"
        print -P ""
        print -P "${_rigel_color_green}Utility Functions:${_rigel_color_reset}"
        print -P "  ${_rigel_color_yellow}rigel_license${_rigel_color_reset}                    — Show license information"
        print -P "  ${_rigel_color_yellow}rigel_status${_rigel_color_reset}                     — Check service health"
        print -P "  ${_rigel_color_yellow}rigel_debug${_rigel_color_reset}                      — Run D-Bus diagnostics"
        print -P "  ${_rigel_color_yellow}rigel_help${_rigel_color_reset}                       — Show this help message"
        print -P "  ${_rigel_color_yellow}rigel_config${_rigel_color_reset}                    — Re-run configuration wizard"
        print -P "  ${_rigel_color_yellow}rigel_update${_rigel_color_reset}                    — Update RIGEL engine"
        print -P ""
        print -P "${_rigel_color_green}Logging Functions:${_rigel_color_reset}"
        print -P "  ${_rigel_color_yellow}rigel_info${_rigel_color_reset} 'message'             — Log info message"
        print -P "  ${_rigel_color_yellow}rigel_warn${_rigel_color_reset} 'message'             — Log warning message"
        print -P "  ${_rigel_color_yellow}rigel_error${_rigel_color_reset} 'message'            — Log error message"
        print -P "  ${_rigel_color_yellow}rigel_success${_rigel_color_reset} 'message'          — Log success message"
        print -P ""
        print -P "${_rigel_color_blue}Examples:${_rigel_color_reset}"
        print -P "  rigel_query 'What is the weather like today?'"
        print -P "  rigel_memory 'chat_001' 'What did we discuss earlier?'"
        print -P "  rigel_think 'Explain the theory of relativity'"
        print -P "  rigel_tools 'Create a Python script to list files'"
        print -P "  rigel_natural_language 'check system load and explain simply'"
        print -P "  rigel_speak 'Hello world' chunk hal"
        print -P "  rigel_transcribe '/home/user/audio.wav' small"
        print -P "  rigel_vision '/tmp/screenshot.png' 'What is on the screen?'"
        print -P ""
        print -P "${_rigel_color_cyan}Troubleshooting:${_rigel_color_reset}"
        print -P "  Run ${_rigel_color_yellow}rigel_status${_rigel_color_reset} to check service health"
        print -P "  Run ${_rigel_color_yellow}rigel_debug${_rigel_color_reset} to diagnose D-Bus connection issues"
        print -P ""
        print -P "${_rigel_color_cyan}For more information, visit: https://github.com/Zerone-Laboratories/RIGEL${_rigel_color_reset}"
    else
        echo -e "${_rigel_color_cyan}RIGEL Runtime — Intelligent Functions${_rigel_color_reset}"
        echo ""
        echo -e "${_rigel_color_green}Basic Functions:${_rigel_color_reset}"
        echo "  rigel_query [--no_animate] 'question' — Ask RIGEL a question"
        echo "  rigel_memory 'id' 'question'          — Ask with conversation memory"
        echo "  rigel_think 'question'              — Think/reason before answering"
        echo "  rigel_tools 'task'                    — Use RIGEL with MCP tools"
        echo "  rigel_natural_language [id] 'request' — Memory-first natural language flow"
        echo "  rigel_nl [id] 'request'               — Short alias for rigel_natural_language"
        echo ""
        echo -e "${_rigel_color_green}Voice Functions:${_rigel_color_reset}"
        echo "  rigel_speak 'text' [mode] [voice] — Text-to-speech synthesis"
        echo "  rigel_transcribe '/path' [model]   — Audio-to-text transcription"
        echo "  rigel_voice_list                     — List available voices"
        echo "  rigel_voice_set 'name'            — Switch TTS voice"
        echo "  rigel_voice_clone 'mp3' 'name'   — Clone a voice from audio"
        echo "  rigel_live_transcribe start|stop|status — Live voice recognition"
        echo ""
        echo -e "${_rigel_color_green}Vision:${_rigel_color_reset}"
        echo "  rigel_vision 'image.png' [prompt] — Analyze an image"
        echo ""
        echo -e "${_rigel_color_green}Coding Agent:${_rigel_color_reset}"
        echo "  rigel_coding_generate 'spec' [lang]  — Generate code from spec"
        echo "  rigel_coding_review 'file' [lang]   — Review code"
        echo "  rigel_coding_debug 'file' 'err' [lang] — Debug code with error"
        echo "  rigel_coding_refactor 'file' 'instr' [lang] — Refactor code"
        echo "  rigel_coding_explain 'file' [lang]  — Explain code"
        echo "  rigel_coding_execute 'file' [args] — Execute code"
        echo "  rigel_coding_status                  — Coding agent status"
        echo "  rigel_coding_history [n]           — Coding agent history"
        echo "  rigel_coding_launch                  — Launch coding agent"
        echo "  rigel_coding_close                   — Close coding agent"
        echo ""
        echo -e "${_rigel_color_green}Utility:${_rigel_color_reset}"
        echo "  rigel_license — License info  | rigel_status  — Service health"
        echo "  rigel_debug   — D-Bus diagnostics | rigel_help   — This help"
        echo "  rigel_config  — Re-run config wizard | rigel_update — Update RIGEL"
        echo ""
        echo "Type 'rigel_help' for more details."
        echo -e "${_rigel_color_cyan}https://github.com/Zerone-Laboratories/RIGEL${_rigel_color_reset}"
    fi
}

# ── Status prompt ────────────────────────────────────────────────────────────
rigel_status_prompt() {
    if _rigel_service_running 2>/dev/null; then
        if [[ -n "$ZSH_VERSION" ]]; then
            echo "%F{black}%K{green} [0] %k%f"
        else
            echo -e "\033[30m\033[42m [0] \033[0m"
        fi
    else
        if [[ -n "$ZSH_VERSION" ]]; then
            echo "%F{white}%K{red} < ! > %k%f"
        else
            echo -e "\033[37m\033[41m < ! > \033[0m"
        fi
    fi
}

# ── Config & Update ──────────────────────────────────────────────────────────
rigel_config() {
    local wizard_path="$_RIGEL_INSTALL_DIR/rigel-config-wizard.py"

    if [[ -f "$wizard_path" ]]; then
        rigel_info "Launching RIGEL configuration wizard..."
        if command -v python3 &>/dev/null; then
            python3 "$wizard_path" "$_RIGEL_INSTALL_DIR"
        elif command -v python &>/dev/null; then
            python "$wizard_path" "$_RIGEL_INSTALL_DIR"
        else
            rigel_error "Python not found. Please edit $_RIGEL_INSTALL_DIR/.env manually."
            return 1
        fi
    else
        rigel_warn "Config wizard not found at $wizard_path"
        rigel_info "Opening .env in editor..."
        "${EDITOR:-nano}" "$_RIGEL_INSTALL_DIR/.env"
    fi

    rigel_info "Configuration updated. Restart RIGEL for changes to take effect:"
    rigel_info "  sudo docker compose -f $_RIGEL_INSTALL_DIR/docker-compose.yml restart"
}

rigel_update() {
    local rigel_dir="$_RIGEL_INSTALL_DIR"

    if [[ ! -d "$rigel_dir" ]]; then
        rigel_error "RIGEL install directory not found: $rigel_dir"
        return 1
    fi

    rigel_info "Updating RIGEL engine from $rigel_dir..."

    if ! command -v docker &>/dev/null; then
        rigel_error "Docker is not installed."
        return 1
    fi

    cd "$rigel_dir" || return 1

    rigel_info "Pulling latest changes..."
    if ! git pull 2>&1; then
        rigel_error "Git pull failed. Check your network or repository state."
        return 1
    fi

    rigel_info "Rebuilding Docker image..."
    if ! docker compose build --build-arg SKIP_PYTHON_DEPS=false 2>&1; then
        rigel_error "Docker build failed. Check the logs above."
        return 1
    fi

    rigel_info "Restarting RIGEL server..."
    if docker compose up -d rigel-server 2>&1; then
        rigel_success "RIGEL engine updated and restarted successfully!"
    else
        rigel_error "Failed to restart RIGEL server. Check logs: docker compose -f $rigel_dir/docker-compose.yml logs"
        return 1
    fi
}

# ── Server type check ────────────────────────────────────────────────────────
_rigel_check_server_type() {
    local env_file="$_RIGEL_INSTALL_DIR/.env"
    if [[ -f "$env_file" ]]; then
        local server_type
        server_type=$(grep -E '^SERVER_TYPE=' "$env_file" 2>/dev/null | cut -d= -f2 | tr -d '"' | tr -d "'")
        if [[ "$server_type" == "web" ]]; then
            return 0  # web-only mode
        fi
    fi
    return 1  # hybrid, dbus, or unknown
}

# ── Startup banner ───────────────────────────────────────────────────────────
_rigel_startup() {
    if [[ -n "$ZSH_VERSION" ]]; then
        print -P "\n${_rigel_color_magenta}╔═══════════════════════════════════════════════════════════════╗${_rigel_color_reset}"
        print -P "${_rigel_color_magenta} ║${_rigel_color_reset}    ${_rigel_color_bold}${_rigel_color_cyan}RIGEL Runtime Shell Integration v2.0${_rigel_color_bold_off}${_rigel_color_reset}${_rigel_color_magenta} ║${_rigel_color_reset}"
        print -P "${_rigel_color_magenta}╚═══════════════════════════════════════════════════════════════╝${_rigel_color_reset}"
    else
        echo ""
        echo -e "${_rigel_color_magenta}=== RIGEL Runtime Shell Integration v2.0 ===${_rigel_color_reset}"
    fi

    if _rigel_service_running 2>/dev/null; then
        rigel_success "RIGEL D-Bus service is active"
        rigel_info "Intelligent Functions and Multi-Agent Systems are available."
        rigel_info "Type 'rigel_help' for detailed usage information."
    else
        rigel_warn "RIGEL D-Bus service is not active."
        rigel_info "Install and start the RIGEL service to enable intelligent functions."
        rigel_info "Guide: https://github.com/Zerone-Laboratories/RIGEL"
        rigel_info "Use 'rigel_debug' to troubleshoot D-Bus connection issues."
    fi

    # Warn if server is web-only (no D-Bus service)
    if _rigel_check_server_type; then
        if [[ -n "$ZSH_VERSION" ]]; then
            print -P "\n${_rigel_color_bold}${_rigel_color_red}⚠ WARNING:${_rigel_color_reset} ${_rigel_color_yellow}Shell commands will not work without the DBus Server!${_rigel_color_reset}"
            print -P "${_rigel_color_dim}  The server is configured as web-only (SERVER_TYPE=web)."
            print -P "  Run ${_rigel_color_yellow}rigel_config${_rigel_color_dim} and select 'hybrid' or 'dbus' to enable shell commands.${_rigel_color_reset}"
        else
            echo -e "\n${_rigel_color_bold}${_rigel_color_red}WARNING:${_rigel_color_reset} ${_rigel_color_yellow}Shell commands will not work without the DBus Server!${_rigel_color_reset}"
            echo -e "${_rigel_color_dim}  The server is configured as web-only (SERVER_TYPE=web)."
            echo -e "  Run rigel_config and select 'hybrid' or 'dbus' to enable shell commands.${_rigel_color_reset}"
        fi
    fi
}

# ── Run startup banner (but not in non-interactive shells) ───────────────────
# Only show banner in interactive shells to avoid breaking scp/sftp
if [[ $- == *i* ]]; then
    _rigel_startup
fi
