name: Project Health Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13.3'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgirepository1.0-dev \
          libgirepository-2.0-dev \
          libglib2.0-dev \
          pkg-config \
          python3-dev \
          libgtk-3-dev \
          gobject-introspection \
          gir1.2-glib-2.0 \
          pulseaudio \
          pulseaudio-utils \
          ffmpeg \
          build-essential \
          libblas-dev \
          liblapack-dev \
          gfortran
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Pin setuptools to avoid pkg_resources deprecation issues with openai-whisper
        pip install "setuptools<81"
        # Install dependencies with specific handling for problematic packages
        if [ -f requirements.txt ]; then 
          # Try installing everything normally first
          pip install -r requirements.txt || {
            echo "Standard installation failed, trying alternative approach..."
            # Install without openai-whisper first to avoid conflicts
            grep -v "openai-whisper" requirements.txt | pip install -r /dev/stdin
            # Try installing openai-whisper with no-deps and manual dependencies
            pip install openai-whisper==20240930 --no-deps || {
              echo "openai-whisper installation failed, trying faster-whisper as alternative..."
              pip install faster-whisper
            }
            # Install whisper dependencies manually if needed
            pip install tiktoken more-itertools
          }
        fi
    
    - name: Validate project structure
      run: |
        echo "Project structure validation passed"
        echo "Core modules found:"
        ls -la core/
        echo "README.md exists and is readable"
        head -n 5 README.md
        
    - name: Test voice module imports
      run: |
        python -c "
        whisper_available = False
        
        # Try openai-whisper first
        try:
            import whisper
            print('✓ OpenAI Whisper import successful')
            whisper_available = True
        except ImportError as e:
            print('⚠ OpenAI Whisper import failed:', str(e))
            
        # Try faster-whisper as fallback
        if not whisper_available:
            try:
                import faster_whisper
                print('✓ Faster Whisper import successful (fallback)')
                whisper_available = True
            except ImportError as e:
                print('⚠ Faster Whisper import failed:', str(e))
                
        if not whisper_available:
            print('✗ No whisper implementation available')
            exit(1)
            
        try:
            import torch
            print('✓ PyTorch import successful')
        except ImportError as e:
            print('✗ PyTorch import failed:', e)
            exit(1)
        "
        
    - name: Test core module imports
      run: |
        python -c "
        import sys
        sys.path.append('.')
        
        try:
            from core.logger import SysLog
            print('✓ Logger module import successful')
        except ImportError as e:
            print('✗ Logger module import failed:', e)
            
        try:
            from core.rigel import Rigel
            print('✓ Rigel core module import successful')
        except ImportError as e:
            print('✗ Rigel core module import failed:', e)
            
        try:
            from core.synth_n_recog import Synthesizer, Recognizer
            print('✓ Voice modules import successful')
        except ImportError as e:
            print('✗ Voice modules import failed:', e)
        "
